{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "gather": {
     "logged": 1598275788035
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Workspace name: quick-starts-ws-122756\n",
      "Azure region: southcentralus\n",
      "Subscription id: 502bce8d-d66b-4661-a423-f21e61d20123\n",
      "Resource group: aml-quickstarts-122756\n"
     ]
    }
   ],
   "source": [
    "from azureml.core import Workspace, Experiment\n",
    "\n",
    "ws = Workspace.get(name=\"quick-starts-ws-122756\")\n",
    "\n",
    "exp = Experiment(workspace=ws, name=\"udacity-project\")\n",
    "\n",
    "print('Workspace name: ' + ws.name, \n",
    "      'Azure region: ' + ws.location, \n",
    "      'Subscription id: ' + ws.subscription_id, \n",
    "      'Resource group: ' + ws.resource_group, sep = '\\n')\n",
    "\n",
    "run = exp.start_logging()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {
    "gather": {
     "logged": 1598275788675
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "from azureml.core.compute import ComputeTarget, AmlCompute\n",
    "# TODO: Create compute cluster\n",
    "# Use vm_size = \"Standard_D2_V2\" in your provisioning configuration.\n",
    "# max_nodes should be no greater than 4.\n",
    "\n",
    "### YOUR CODE HERE ###\n",
    "comp_cluster = 'opt-ml-cluster'\n",
    "comp_confg = AmlCompute.provisioning_configuration(vm_size='Standard_D2_V2', max_nodes=4, min_nodes=1)\n",
    "comp_trget = ComputeTarget.create(ws, comp_cluster, comp_confg)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "project1 ComputeInstance Succeeded\n",
      "opt-ml-cluster AmlCompute Succeeded\n"
     ]
    }
   ],
   "source": [
    "comp_trgets = ws.compute_targets\n",
    "for comp_name,comp_type in comp_trgets.items():\n",
    "    print(comp_name,comp_type.type,comp_type.provisioning_state)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {
    "gather": {
     "logged": 1598275789986
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "from azureml.widgets import RunDetails\n",
    "from azureml.train.sklearn import SKLearn\n",
    "from azureml.train.hyperdrive.run import PrimaryMetricGoal\n",
    "from azureml.train.hyperdrive.policy import BanditPolicy\n",
    "from azureml.train.hyperdrive.sampling import RandomParameterSampling\n",
    "from azureml.train.hyperdrive.runconfig import HyperDriveConfig\n",
    "from azureml.train.hyperdrive.parameter_expressions import uniform,choice\n",
    "import os\n",
    "\n",
    "# Specify parameter sampler\n",
    "ps = RandomParameterSampling(\n",
    "{\n",
    "    '--batch-size' : choice(25,50,75,100),\n",
    "    '--learning-rate' : uniform(0.07,1)\n",
    "})\n",
    "\n",
    "# Specify a Policy\n",
    "policy = BanditPolicy(evaluation_interval = 3, slack_factor = 0.1)\n",
    "\n",
    "if \"training\" not in os.listdir():\n",
    "    os.mkdir(\"./training\")\n",
    "\n",
    "# Create a SKLearn estimator for use with train.py\n",
    "est = SKLearn(\n",
    "    source_directory = '.',\n",
    "    compute_target = comp_trget,\n",
    "    entry_script = 'train.py'\n",
    ")\n",
    "\n",
    "# Create a HyperDriveConfig using the estimator, hyperparameter sampler, and policy.\n",
    "hyperdrive_config = HyperDriveConfig (\n",
    "    hyperparameter_sampling=ps,\n",
    "    primary_metric_name='Accuracy',\n",
    "    primary_metric_goal=PrimaryMetricGoal.MAXIMIZE,\n",
    "    max_total_runs=40,\n",
    "    max_concurrent_runs=5,\n",
    "    policy=policy,\n",
    "    estimator=est\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "RunId: HD_402d014f-07d3-4c64-b158-86d3d0890819\n",
      "Web View: https://ml.azure.com/experiments/udacity-project/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819?wsid=/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourcegroups/aml-quickstarts-122756/workspaces/quick-starts-ws-122756\n",
      "\n",
      "Streaming azureml-logs/hyperdrive.txt\n",
      "=====================================\n",
      "\n",
      "\"<START>[2020-10-25T05:18:02.712826][API][INFO]Experiment created<END>\\n\"\"<START>[2020-10-25T05:18:03.791644][GENERATOR][INFO]Trying to sample '5' jobs from the hyperparameter space<END>\\n\"\"<START>[2020-10-25T05:18:04.279677][GENERATOR][INFO]Successfully sampled '5' jobs, they will soon be submitted to the execution target.<END>\\n\"<START>[2020-10-25T05:18:05.0309346Z][SCHEDULER][INFO]The execution environment is being prepared. Please be patient as it can take a few minutes.<END>\n",
      "\n",
      "Execution Summary\n",
      "=================\n",
      "RunId: HD_402d014f-07d3-4c64-b158-86d3d0890819\n",
      "Web View: https://ml.azure.com/experiments/udacity-project/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819?wsid=/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourcegroups/aml-quickstarts-122756/workspaces/quick-starts-ws-122756\n",
      "\n",
      "Warnings:\n",
      "{\n",
      "  \"error\": {\n",
      "    \"code\": \"UserError\",\n",
      "    \"severity\": null,\n",
      "    \"message\": \"User errors were found in at least one of the child runs.\",\n",
      "    \"messageFormat\": null,\n",
      "    \"messageParameters\": {},\n",
      "    \"referenceCode\": null,\n",
      "    \"detailsUri\": null,\n",
      "    \"target\": null,\n",
      "    \"details\": [],\n",
      "    \"innerError\": null,\n",
      "    \"debugInfo\": {\n",
      "      \"type\": null,\n",
      "      \"message\": \"[(https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_0, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"referenceCode\\\": null,\\n            \\\"messageFormat\\\": null,\\n            \\\"severity\\\": null,\\n            \\\"messageParameters\\\": {}\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with SystemExit: 2\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"SystemExit\\\",\\n            \\\"message\\\": \\\"2\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_0/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_0/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\\\"train.py\\\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 1733, in parse_args\\\\n    self.error(msg % ' '.join(argv))\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 2389, in error\\\\n    self.exit(2, _('%(prog)s: error: %(message)s\\\\\\\\n') % args)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        }\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_1, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"referenceCode\\\": null,\\n            \\\"messageFormat\\\": null,\\n            \\\"severity\\\": null,\\n            \\\"messageParameters\\\": {}\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with SystemExit: 2\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"SystemExit\\\",\\n            \\\"message\\\": \\\"2\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_1/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_1/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\\\"train.py\\\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 1733, in parse_args\\\\n    self.error(msg % ' '.join(argv))\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 2389, in error\\\\n    self.exit(2, _('%(prog)s: error: %(message)s\\\\\\\\n') % args)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        }\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_2, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"referenceCode\\\": null,\\n            \\\"messageFormat\\\": null,\\n            \\\"severity\\\": null,\\n            \\\"messageParameters\\\": {}\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with SystemExit: 2\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"SystemExit\\\",\\n            \\\"message\\\": \\\"2\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_2/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_2/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\\\"train.py\\\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 1733, in parse_args\\\\n    self.error(msg % ' '.join(argv))\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 2389, in error\\\\n    self.exit(2, _('%(prog)s: error: %(message)s\\\\\\\\n') % args)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        }\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_3, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"referenceCode\\\": null,\\n            \\\"messageFormat\\\": null,\\n            \\\"severity\\\": null,\\n            \\\"messageParameters\\\": {}\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with SystemExit: 2\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"SystemExit\\\",\\n            \\\"message\\\": \\\"2\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_3/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_3/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\\\"train.py\\\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 1733, in parse_args\\\\n    self.error(msg % ' '.join(argv))\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 2389, in error\\\\n    self.exit(2, _('%(prog)s: error: %(message)s\\\\\\\\n') % args)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        }\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_4, {'error': {\\n    \\\"additional_properties\\\": {\\n        \\\"componentName\\\": null\\n    },\\n    \\\"error\\\": {\\n        \\\"additional_properties\\\": {\\n            \\\"referenceCode\\\": null,\\n            \\\"messageFormat\\\": null,\\n            \\\"severity\\\": null,\\n            \\\"messageParameters\\\": {}\\n        },\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"User program failed with SystemExit: 2\\\",\\n        \\\"details_uri\\\": \\\"https://aka.ms/azureml-known-errors\\\",\\n        \\\"target\\\": null,\\n        \\\"details\\\": [],\\n        \\\"inner_error\\\": null,\\n        \\\"debug_info\\\": {\\n            \\\"additional_properties\\\": {},\\n            \\\"type\\\": \\\"SystemExit\\\",\\n            \\\"message\\\": \\\"2\\\",\\n            \\\"stack_trace\\\": \\\"  File \\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_4/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_4/azureml-setup/context_manager_injector.py\\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\"__main__\\\\\\\")\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\\"train.py\\\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\\\"train.py\\\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 1733, in parse_args\\\\n    self.error(msg % ' '.join(argv))\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 2389, in error\\\\n    self.exit(2, _('%(prog)s: error: %(message)s\\\\\\\\n') % args)\\\\n  File \\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\\\",\\n            \\\"inner_exception\\\": null,\\n            \\\"data\\\": null,\\n            \\\"error_response\\\": null\\n        }\\n    },\\n    \\\"correlation\\\": null,\\n    \\\"environment\\\": null,\\n    \\\"location\\\": null,\\n    \\\"time\\\": {}\\n}})]\",\n",
      "      \"stackTrace\": null,\n",
      "      \"innerException\": null,\n",
      "      \"data\": null,\n",
      "      \"errorResponse\": null\n",
      "    }\n",
      "  },\n",
      "  \"correlation\": null,\n",
      "  \"environment\": null,\n",
      "  \"location\": null,\n",
      "  \"time\": \"0001-01-01T00:00:00+00:00\",\n",
      "  \"componentName\": null\n",
      "}\n",
      "\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'runId': 'HD_402d014f-07d3-4c64-b158-86d3d0890819',\n",
       " 'target': 'opt-ml-cluster',\n",
       " 'status': 'Canceled',\n",
       " 'startTimeUtc': '2020-10-25T05:18:01.922729Z',\n",
       " 'endTimeUtc': '2020-10-25T05:22:35.704274Z',\n",
       " 'error': {'error': {'code': 'UserError',\n",
       "   'message': 'User errors were found in at least one of the child runs.',\n",
       "   'details': [],\n",
       "   'debugInfo': {'message': '[(https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_0, {\\'error\\': {\\n    \"additional_properties\": {\\n        \"componentName\": null\\n    },\\n    \"error\": {\\n        \"additional_properties\": {\\n            \"referenceCode\": null,\\n            \"messageFormat\": null,\\n            \"severity\": null,\\n            \"messageParameters\": {}\\n        },\\n        \"code\": \"UserError\",\\n        \"message\": \"User program failed with SystemExit: 2\",\\n        \"details_uri\": \"https://aka.ms/azureml-known-errors\",\\n        \"target\": null,\\n        \"details\": [],\\n        \"inner_error\": null,\\n        \"debug_info\": {\\n            \"additional_properties\": {},\\n            \"type\": \"SystemExit\",\\n            \"message\": \"2\",\\n            \"stack_trace\": \"  File \\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_0/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_0/azureml-setup/context_manager_injector.py\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\"__main__\\\\\")\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\"train.py\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\"train.py\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 1733, in parse_args\\\\n    self.error(msg % \\' \\'.join(argv))\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 2389, in error\\\\n    self.exit(2, _(\\'%(prog)s: error: %(message)s\\\\\\\\n\\') % args)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\",\\n            \"inner_exception\": null,\\n            \"data\": null,\\n            \"error_response\": null\\n        }\\n    },\\n    \"correlation\": null,\\n    \"environment\": null,\\n    \"location\": null,\\n    \"time\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_1, {\\'error\\': {\\n    \"additional_properties\": {\\n        \"componentName\": null\\n    },\\n    \"error\": {\\n        \"additional_properties\": {\\n            \"referenceCode\": null,\\n            \"messageFormat\": null,\\n            \"severity\": null,\\n            \"messageParameters\": {}\\n        },\\n        \"code\": \"UserError\",\\n        \"message\": \"User program failed with SystemExit: 2\",\\n        \"details_uri\": \"https://aka.ms/azureml-known-errors\",\\n        \"target\": null,\\n        \"details\": [],\\n        \"inner_error\": null,\\n        \"debug_info\": {\\n            \"additional_properties\": {},\\n            \"type\": \"SystemExit\",\\n            \"message\": \"2\",\\n            \"stack_trace\": \"  File \\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_1/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_1/azureml-setup/context_manager_injector.py\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\"__main__\\\\\")\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\"train.py\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\"train.py\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 1733, in parse_args\\\\n    self.error(msg % \\' \\'.join(argv))\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 2389, in error\\\\n    self.exit(2, _(\\'%(prog)s: error: %(message)s\\\\\\\\n\\') % args)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\",\\n            \"inner_exception\": null,\\n            \"data\": null,\\n            \"error_response\": null\\n        }\\n    },\\n    \"correlation\": null,\\n    \"environment\": null,\\n    \"location\": null,\\n    \"time\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_2, {\\'error\\': {\\n    \"additional_properties\": {\\n        \"componentName\": null\\n    },\\n    \"error\": {\\n        \"additional_properties\": {\\n            \"referenceCode\": null,\\n            \"messageFormat\": null,\\n            \"severity\": null,\\n            \"messageParameters\": {}\\n        },\\n        \"code\": \"UserError\",\\n        \"message\": \"User program failed with SystemExit: 2\",\\n        \"details_uri\": \"https://aka.ms/azureml-known-errors\",\\n        \"target\": null,\\n        \"details\": [],\\n        \"inner_error\": null,\\n        \"debug_info\": {\\n            \"additional_properties\": {},\\n            \"type\": \"SystemExit\",\\n            \"message\": \"2\",\\n            \"stack_trace\": \"  File \\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_2/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_2/azureml-setup/context_manager_injector.py\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\"__main__\\\\\")\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\"train.py\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\"train.py\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 1733, in parse_args\\\\n    self.error(msg % \\' \\'.join(argv))\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 2389, in error\\\\n    self.exit(2, _(\\'%(prog)s: error: %(message)s\\\\\\\\n\\') % args)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\",\\n            \"inner_exception\": null,\\n            \"data\": null,\\n            \"error_response\": null\\n        }\\n    },\\n    \"correlation\": null,\\n    \"environment\": null,\\n    \"location\": null,\\n    \"time\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_3, {\\'error\\': {\\n    \"additional_properties\": {\\n        \"componentName\": null\\n    },\\n    \"error\": {\\n        \"additional_properties\": {\\n            \"referenceCode\": null,\\n            \"messageFormat\": null,\\n            \"severity\": null,\\n            \"messageParameters\": {}\\n        },\\n        \"code\": \"UserError\",\\n        \"message\": \"User program failed with SystemExit: 2\",\\n        \"details_uri\": \"https://aka.ms/azureml-known-errors\",\\n        \"target\": null,\\n        \"details\": [],\\n        \"inner_error\": null,\\n        \"debug_info\": {\\n            \"additional_properties\": {},\\n            \"type\": \"SystemExit\",\\n            \"message\": \"2\",\\n            \"stack_trace\": \"  File \\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_3/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_3/azureml-setup/context_manager_injector.py\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\"__main__\\\\\")\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\"train.py\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\"train.py\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 1733, in parse_args\\\\n    self.error(msg % \\' \\'.join(argv))\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 2389, in error\\\\n    self.exit(2, _(\\'%(prog)s: error: %(message)s\\\\\\\\n\\') % args)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\",\\n            \"inner_exception\": null,\\n            \"data\": null,\\n            \"error_response\": null\\n        }\\n    },\\n    \"correlation\": null,\\n    \"environment\": null,\\n    \"location\": null,\\n    \"time\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_4, {\\'error\\': {\\n    \"additional_properties\": {\\n        \"componentName\": null\\n    },\\n    \"error\": {\\n        \"additional_properties\": {\\n            \"referenceCode\": null,\\n            \"messageFormat\": null,\\n            \"severity\": null,\\n            \"messageParameters\": {}\\n        },\\n        \"code\": \"UserError\",\\n        \"message\": \"User program failed with SystemExit: 2\",\\n        \"details_uri\": \"https://aka.ms/azureml-known-errors\",\\n        \"target\": null,\\n        \"details\": [],\\n        \"inner_error\": null,\\n        \"debug_info\": {\\n            \"additional_properties\": {},\\n            \"type\": \"SystemExit\",\\n            \"message\": \"2\",\\n            \"stack_trace\": \"  File \\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_4/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_4/azureml-setup/context_manager_injector.py\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\"__main__\\\\\")\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\"train.py\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\"train.py\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 1733, in parse_args\\\\n    self.error(msg % \\' \\'.join(argv))\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 2389, in error\\\\n    self.exit(2, _(\\'%(prog)s: error: %(message)s\\\\\\\\n\\') % args)\\\\n  File \\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\",\\n            \"inner_exception\": null,\\n            \"data\": null,\\n            \"error_response\": null\\n        }\\n    },\\n    \"correlation\": null,\\n    \"environment\": null,\\n    \"location\": null,\\n    \"time\": {}\\n}})]'},\n",
       "   'messageParameters': {}},\n",
       "  'time': '0001-01-01T00:00:00.000Z'},\n",
       " 'warnings': [{'source': 'SecondaryError',\n",
       "   'message': '{\\n  \"error\": {\\n    \"code\": \"UserError\",\\n    \"severity\": null,\\n    \"message\": \"User errors were found in at least one of the child runs.\",\\n    \"messageFormat\": null,\\n    \"messageParameters\": {},\\n    \"referenceCode\": null,\\n    \"detailsUri\": null,\\n    \"target\": null,\\n    \"details\": [],\\n    \"innerError\": null,\\n    \"debugInfo\": {\\n      \"type\": null,\\n      \"message\": \"[(https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_0, {\\'error\\': {\\\\n    \\\\\"additional_properties\\\\\": {\\\\n        \\\\\"componentName\\\\\": null\\\\n    },\\\\n    \\\\\"error\\\\\": {\\\\n        \\\\\"additional_properties\\\\\": {\\\\n            \\\\\"referenceCode\\\\\": null,\\\\n            \\\\\"messageFormat\\\\\": null,\\\\n            \\\\\"severity\\\\\": null,\\\\n            \\\\\"messageParameters\\\\\": {}\\\\n        },\\\\n        \\\\\"code\\\\\": \\\\\"UserError\\\\\",\\\\n        \\\\\"message\\\\\": \\\\\"User program failed with SystemExit: 2\\\\\",\\\\n        \\\\\"details_uri\\\\\": \\\\\"https://aka.ms/azureml-known-errors\\\\\",\\\\n        \\\\\"target\\\\\": null,\\\\n        \\\\\"details\\\\\": [],\\\\n        \\\\\"inner_error\\\\\": null,\\\\n        \\\\\"debug_info\\\\\": {\\\\n            \\\\\"additional_properties\\\\\": {},\\\\n            \\\\\"type\\\\\": \\\\\"SystemExit\\\\\",\\\\n            \\\\\"message\\\\\": \\\\\"2\\\\\",\\\\n            \\\\\"stack_trace\\\\\": \\\\\"  File \\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_0/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_0/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\"train.py\\\\\\\\\\\\\", line 81, in <module>\\\\\\\\n    main()\\\\\\\\n  File \\\\\\\\\\\\\"train.py\\\\\\\\\\\\\", line 67, in main\\\\\\\\n    args = parser.parse_args()\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 1733, in parse_args\\\\\\\\n    self.error(msg % \\' \\'.join(argv))\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 2389, in error\\\\\\\\n    self.exit(2, _(\\'%(prog)s: error: %(message)s\\\\\\\\\\\\\\\\n\\') % args)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 2376, in exit\\\\\\\\n    _sys.exit(status)\\\\\\\\n\\\\\",\\\\n            \\\\\"inner_exception\\\\\": null,\\\\n            \\\\\"data\\\\\": null,\\\\n            \\\\\"error_response\\\\\": null\\\\n        }\\\\n    },\\\\n    \\\\\"correlation\\\\\": null,\\\\n    \\\\\"environment\\\\\": null,\\\\n    \\\\\"location\\\\\": null,\\\\n    \\\\\"time\\\\\": {}\\\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_1, {\\'error\\': {\\\\n    \\\\\"additional_properties\\\\\": {\\\\n        \\\\\"componentName\\\\\": null\\\\n    },\\\\n    \\\\\"error\\\\\": {\\\\n        \\\\\"additional_properties\\\\\": {\\\\n            \\\\\"referenceCode\\\\\": null,\\\\n            \\\\\"messageFormat\\\\\": null,\\\\n            \\\\\"severity\\\\\": null,\\\\n            \\\\\"messageParameters\\\\\": {}\\\\n        },\\\\n        \\\\\"code\\\\\": \\\\\"UserError\\\\\",\\\\n        \\\\\"message\\\\\": \\\\\"User program failed with SystemExit: 2\\\\\",\\\\n        \\\\\"details_uri\\\\\": \\\\\"https://aka.ms/azureml-known-errors\\\\\",\\\\n        \\\\\"target\\\\\": null,\\\\n        \\\\\"details\\\\\": [],\\\\n        \\\\\"inner_error\\\\\": null,\\\\n        \\\\\"debug_info\\\\\": {\\\\n            \\\\\"additional_properties\\\\\": {},\\\\n            \\\\\"type\\\\\": \\\\\"SystemExit\\\\\",\\\\n            \\\\\"message\\\\\": \\\\\"2\\\\\",\\\\n            \\\\\"stack_trace\\\\\": \\\\\"  File \\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_1/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_1/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\"train.py\\\\\\\\\\\\\", line 81, in <module>\\\\\\\\n    main()\\\\\\\\n  File \\\\\\\\\\\\\"train.py\\\\\\\\\\\\\", line 67, in main\\\\\\\\n    args = parser.parse_args()\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 1733, in parse_args\\\\\\\\n    self.error(msg % \\' \\'.join(argv))\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 2389, in error\\\\\\\\n    self.exit(2, _(\\'%(prog)s: error: %(message)s\\\\\\\\\\\\\\\\n\\') % args)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 2376, in exit\\\\\\\\n    _sys.exit(status)\\\\\\\\n\\\\\",\\\\n            \\\\\"inner_exception\\\\\": null,\\\\n            \\\\\"data\\\\\": null,\\\\n            \\\\\"error_response\\\\\": null\\\\n        }\\\\n    },\\\\n    \\\\\"correlation\\\\\": null,\\\\n    \\\\\"environment\\\\\": null,\\\\n    \\\\\"location\\\\\": null,\\\\n    \\\\\"time\\\\\": {}\\\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_2, {\\'error\\': {\\\\n    \\\\\"additional_properties\\\\\": {\\\\n        \\\\\"componentName\\\\\": null\\\\n    },\\\\n    \\\\\"error\\\\\": {\\\\n        \\\\\"additional_properties\\\\\": {\\\\n            \\\\\"referenceCode\\\\\": null,\\\\n            \\\\\"messageFormat\\\\\": null,\\\\n            \\\\\"severity\\\\\": null,\\\\n            \\\\\"messageParameters\\\\\": {}\\\\n        },\\\\n        \\\\\"code\\\\\": \\\\\"UserError\\\\\",\\\\n        \\\\\"message\\\\\": \\\\\"User program failed with SystemExit: 2\\\\\",\\\\n        \\\\\"details_uri\\\\\": \\\\\"https://aka.ms/azureml-known-errors\\\\\",\\\\n        \\\\\"target\\\\\": null,\\\\n        \\\\\"details\\\\\": [],\\\\n        \\\\\"inner_error\\\\\": null,\\\\n        \\\\\"debug_info\\\\\": {\\\\n            \\\\\"additional_properties\\\\\": {},\\\\n            \\\\\"type\\\\\": \\\\\"SystemExit\\\\\",\\\\n            \\\\\"message\\\\\": \\\\\"2\\\\\",\\\\n            \\\\\"stack_trace\\\\\": \\\\\"  File \\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_2/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_2/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\"train.py\\\\\\\\\\\\\", line 81, in <module>\\\\\\\\n    main()\\\\\\\\n  File \\\\\\\\\\\\\"train.py\\\\\\\\\\\\\", line 67, in main\\\\\\\\n    args = parser.parse_args()\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 1733, in parse_args\\\\\\\\n    self.error(msg % \\' \\'.join(argv))\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 2389, in error\\\\\\\\n    self.exit(2, _(\\'%(prog)s: error: %(message)s\\\\\\\\\\\\\\\\n\\') % args)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 2376, in exit\\\\\\\\n    _sys.exit(status)\\\\\\\\n\\\\\",\\\\n            \\\\\"inner_exception\\\\\": null,\\\\n            \\\\\"data\\\\\": null,\\\\n            \\\\\"error_response\\\\\": null\\\\n        }\\\\n    },\\\\n    \\\\\"correlation\\\\\": null,\\\\n    \\\\\"environment\\\\\": null,\\\\n    \\\\\"location\\\\\": null,\\\\n    \\\\\"time\\\\\": {}\\\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_3, {\\'error\\': {\\\\n    \\\\\"additional_properties\\\\\": {\\\\n        \\\\\"componentName\\\\\": null\\\\n    },\\\\n    \\\\\"error\\\\\": {\\\\n        \\\\\"additional_properties\\\\\": {\\\\n            \\\\\"referenceCode\\\\\": null,\\\\n            \\\\\"messageFormat\\\\\": null,\\\\n            \\\\\"severity\\\\\": null,\\\\n            \\\\\"messageParameters\\\\\": {}\\\\n        },\\\\n        \\\\\"code\\\\\": \\\\\"UserError\\\\\",\\\\n        \\\\\"message\\\\\": \\\\\"User program failed with SystemExit: 2\\\\\",\\\\n        \\\\\"details_uri\\\\\": \\\\\"https://aka.ms/azureml-known-errors\\\\\",\\\\n        \\\\\"target\\\\\": null,\\\\n        \\\\\"details\\\\\": [],\\\\n        \\\\\"inner_error\\\\\": null,\\\\n        \\\\\"debug_info\\\\\": {\\\\n            \\\\\"additional_properties\\\\\": {},\\\\n            \\\\\"type\\\\\": \\\\\"SystemExit\\\\\",\\\\n            \\\\\"message\\\\\": \\\\\"2\\\\\",\\\\n            \\\\\"stack_trace\\\\\": \\\\\"  File \\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_3/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_3/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\"train.py\\\\\\\\\\\\\", line 81, in <module>\\\\\\\\n    main()\\\\\\\\n  File \\\\\\\\\\\\\"train.py\\\\\\\\\\\\\", line 67, in main\\\\\\\\n    args = parser.parse_args()\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 1733, in parse_args\\\\\\\\n    self.error(msg % \\' \\'.join(argv))\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 2389, in error\\\\\\\\n    self.exit(2, _(\\'%(prog)s: error: %(message)s\\\\\\\\\\\\\\\\n\\') % args)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 2376, in exit\\\\\\\\n    _sys.exit(status)\\\\\\\\n\\\\\",\\\\n            \\\\\"inner_exception\\\\\": null,\\\\n            \\\\\"data\\\\\": null,\\\\n            \\\\\"error_response\\\\\": null\\\\n        }\\\\n    },\\\\n    \\\\\"correlation\\\\\": null,\\\\n    \\\\\"environment\\\\\": null,\\\\n    \\\\\"location\\\\\": null,\\\\n    \\\\\"time\\\\\": {}\\\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_4, {\\'error\\': {\\\\n    \\\\\"additional_properties\\\\\": {\\\\n        \\\\\"componentName\\\\\": null\\\\n    },\\\\n    \\\\\"error\\\\\": {\\\\n        \\\\\"additional_properties\\\\\": {\\\\n            \\\\\"referenceCode\\\\\": null,\\\\n            \\\\\"messageFormat\\\\\": null,\\\\n            \\\\\"severity\\\\\": null,\\\\n            \\\\\"messageParameters\\\\\": {}\\\\n        },\\\\n        \\\\\"code\\\\\": \\\\\"UserError\\\\\",\\\\n        \\\\\"message\\\\\": \\\\\"User program failed with SystemExit: 2\\\\\",\\\\n        \\\\\"details_uri\\\\\": \\\\\"https://aka.ms/azureml-known-errors\\\\\",\\\\n        \\\\\"target\\\\\": null,\\\\n        \\\\\"details\\\\\": [],\\\\n        \\\\\"inner_error\\\\\": null,\\\\n        \\\\\"debug_info\\\\\": {\\\\n            \\\\\"additional_properties\\\\\": {},\\\\n            \\\\\"type\\\\\": \\\\\"SystemExit\\\\\",\\\\n            \\\\\"message\\\\\": \\\\\"2\\\\\",\\\\n            \\\\\"stack_trace\\\\\": \\\\\"  File \\\\\\\\\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_4/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_4/azureml-setup/context_manager_injector.py\\\\\\\\\\\\\", line 181, in execute_with_context\\\\\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\\\\\\\\"__main__\\\\\\\\\\\\\")\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 263, in run_path\\\\\\\\n    pkg_name=pkg_name, script_name=fname)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 96, in _run_module_code\\\\\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\\\\\\\\", line 85, in _run_code\\\\\\\\n    exec(code, run_globals)\\\\\\\\n  File \\\\\\\\\\\\\"train.py\\\\\\\\\\\\\", line 81, in <module>\\\\\\\\n    main()\\\\\\\\n  File \\\\\\\\\\\\\"train.py\\\\\\\\\\\\\", line 67, in main\\\\\\\\n    args = parser.parse_args()\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 1733, in parse_args\\\\\\\\n    self.error(msg % \\' \\'.join(argv))\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 2389, in error\\\\\\\\n    self.exit(2, _(\\'%(prog)s: error: %(message)s\\\\\\\\\\\\\\\\n\\') % args)\\\\\\\\n  File \\\\\\\\\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\\\\\\\\", line 2376, in exit\\\\\\\\n    _sys.exit(status)\\\\\\\\n\\\\\",\\\\n            \\\\\"inner_exception\\\\\": null,\\\\n            \\\\\"data\\\\\": null,\\\\n            \\\\\"error_response\\\\\": null\\\\n        }\\\\n    },\\\\n    \\\\\"correlation\\\\\": null,\\\\n    \\\\\"environment\\\\\": null,\\\\n    \\\\\"location\\\\\": null,\\\\n    \\\\\"time\\\\\": {}\\\\n}})]\",\\n      \"stackTrace\": null,\\n      \"innerException\": null,\\n      \"data\": null,\\n      \"errorResponse\": null\\n    }\\n  },\\n  \"correlation\": null,\\n  \"environment\": null,\\n  \"location\": null,\\n  \"time\": \"0001-01-01T00:00:00+00:00\",\\n  \"componentName\": null\\n}'}],\n",
       " 'properties': {'primary_metric_config': '{\"name\": \"Accuracy\", \"goal\": \"maximize\"}',\n",
       "  'resume_from': 'null',\n",
       "  'runTemplate': 'HyperDrive',\n",
       "  'azureml.runsource': 'hyperdrive',\n",
       "  'platform': 'AML',\n",
       "  'ContentSnapshotId': '921474d0-f2e1-4fc7-90e4-9c6e23e7adab'},\n",
       " 'inputDatasets': [],\n",
       " 'outputDatasets': [],\n",
       " 'logFiles': {'azureml-logs/hyperdrive.txt': 'https://mlstrg122756.blob.core.windows.net/azureml/ExperimentRun/dcid.HD_402d014f-07d3-4c64-b158-86d3d0890819/azureml-logs/hyperdrive.txt?sv=2019-02-02&sr=b&sig=T1BtwIiemhufgagkEEbLFoZbXY1iUNqev0EDsT47aT4%3D&st=2020-10-25T05%3A12%3A36Z&se=2020-10-25T13%3A22%3A36Z&sp=r'}}"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Submit your hyperdrive run to the experiment and show run details with the widget.\n",
    "### YOUR CODE HERE ###\n",
    "hyperdrive_submission = exp.submit(config=hyperdrive_config)\n",
    "hyperdrive_submission.wait_for_completion(show_output=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "gather": {
     "logged": 1598276310862
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "import joblib\n",
    "# Get your best run and save the model from that run.\n",
    "\n",
    "### YOUR CODE HERE ###\n",
    "best_run = hyperdrive_submission.get_best_run_by_primary_metric()\n",
    "print('ID : ',best_run.id)\n",
    "best_metric = best_run.get_metrics()\n",
    "print('Accuracy : ',best_metric['accuracy'])\n",
    "\n",
    "final_model = best_run.register_model(model_name = 'hyper-logistic-model',model_path = '/outputs/model.joblib')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from azureml.data.dataset_factory import TabularDatasetFactory\n",
    "\n",
    "# Create TabularDataset using TabularDatasetFactory\n",
    "# Data is available at: \n",
    "# \"https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/bankmarketing_train.csv\"\n",
    "\n",
    "### YOUR CODE HERE ###\n",
    "data_link = 'https://automlsamplenotebookdata.blob.core.windows.net/automl-sample-notebook-data/bankmarketing_train.csv'\n",
    "input_data = TabularDatasetFactory.from_delimited_files(path=data_link)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "gather": {
     "logged": 1598275726969
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "from train import clean_data\n",
    "\n",
    "# Use the clean_data function to clean your data.\n",
    "x, y = clean_data(input_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "gather": {
     "logged": 1598275665403
    },
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "from azureml.train.automl import AutoMLConfig\n",
    "\n",
    "# Set parameters for AutoMLConfig\n",
    "# NOTE: DO NOT CHANGE THE experiment_timeout_minutes PARAMETER OR YOUR INSTANCE WILL TIME OUT.\n",
    "# If you wish to run the experiment longer, you will need to run this notebook in your own\n",
    "# Azure tenant, which will incur personal costs.\n",
    "automl_config = AutoMLConfig(\n",
    "    experiment_timeout_minutes=30,\n",
    "    task='classification',\n",
    "    primary_metric='accuracy',\n",
    "    training_data=,\n",
    "    label_column_name='outcome',\n",
    "    n_cross_validations=7)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "jupyter": {
     "outputs_hidden": false,
     "source_hidden": false
    },
    "nteract": {
     "transient": {
      "deleting": false
     }
    }
   },
   "outputs": [],
   "source": [
    "# Submit your automl run\n",
    "\n",
    "### YOUR CODE HERE ###\n",
    "class_automl = exp.submit(automl_config, show_output = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Retrieve and save your best automl model.\n",
    "\n",
    "### YOUR CODE HERE ###\n",
    "class_automl, best_fit_model = class_automl.get_output()\n",
    "print(best_fit_model)\n",
    "\n",
    "joblib.dump(best_fit_model, 'outputs/best_fit_automl_model.joblib')"
   ]
  }
 ],
 "metadata": {
  "kernel_info": {
   "name": "python3-azureml"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  },
  "nteract": {
   "version": "nteract-front-end@1.0.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
